// src/routes/public.orders.js
// A6 — POST /api/discounts/validate
// A7 — POST /api/orders
// A8 — GET  /api/orders/track

const router         = require('express').Router();
const { supabaseAdmin } = require('../config/supabase');
const R              = require('../utils/response');
const { validate, validateQuery } = require('../middleware/validate');
const {
  validateDiscountSchema,
  placeOrderSchema,
  trackOrderSchema,
} = require('../validators/public.validators');
const { buildWaLink } = require('../utils/whatsapp');

// A6 — Validate discount code
router.post('/discounts/validate', validate(validateDiscountSchema), async (req, res) => {
  const { code, cart_total } = req.body;

  const { data, error } = await supabaseAdmin
    .rpc('validate_discount', { p_code: code, p_cart_total: cart_total });

  if (error) return R.error(res, 'Validation failed');
  const result = data?.[0];
  return R.success(res, result || { is_valid: false, discount_id: null, discount_amount: 0, error_message: 'Invalid code' });
});

// A7 — Place new order (full checkout submit)
router.post('/orders', validate(placeOrderSchema), async (req, res) => {
  const {
    customer_name, whatsapp_number, email, city, address,
    instagram_handle, order_notes, payment_method, source,
    discount_code, items, subtotal, shipping_fee, discount_amount, total_amount,
  } = req.body;

  // Validate discount code if provided and get discount_id
  let discount_id = null;
  if (discount_code) {
    const { data: discData } = await supabaseAdmin
      .rpc('validate_discount', { p_code: discount_code, p_cart_total: subtotal });
    const discResult = discData?.[0];
    if (!discResult?.is_valid) {
      return R.business(res, discResult?.error_message || 'Invalid discount code');
    }
    discount_id = discResult.discount_id;
  }

  // Validate stock for all items before creating the order
  for (const item of items) {
    const { data: product, error: pErr } = await supabaseAdmin
      .from('products')
      .select('id, name, stock_quantity, status')
      .eq('id', item.product_id)
      .single();

    if (pErr || !product) {
      return R.business(res, `Product not found: ${item.product_id}`);
    }
    if (product.status !== 'active') {
      return R.business(res, `"${product.name}" is no longer available`);
    }
    if (product.stock_quantity < item.quantity) {
      return R.business(res, `Insufficient stock for "${product.name}". Only ${product.stock_quantity} left.`);
    }
  }

  // Create order record (order_number is auto-generated by DB trigger)
  const { data: order, error: orderErr } = await supabaseAdmin
    .from('orders')
    .insert({
      customer_name, whatsapp_number, email: email || null,
      city, address,
      instagram_handle: instagram_handle || null,
      order_notes: order_notes || null,
      payment_method, source, discount_id,
      subtotal, shipping_fee, discount_amount, total_amount,
      status: 'pending_payment',
    })
    .select('id, order_number, status, total_amount, created_at')
    .single();

  if (orderErr) {
    console.error('Order creation error:', orderErr);
    return R.error(res, 'Failed to create order. Please try again.');
  }

  // Insert all order items
  const orderItems = items.map(item => ({
    order_id:     order.id,
    product_id:   item.product_id,
    product_name: item.product_name || '',   // caller should pass product_name
    quantity:     item.quantity,
    unit_price:   item.unit_price,
    subtotal:     item.quantity * item.unit_price,
  }));

  // Fetch product names if not provided
  for (const oi of orderItems) {
    if (!oi.product_name) {
      const { data: p } = await supabaseAdmin
        .from('products').select('name').eq('id', oi.product_id).single();
      oi.product_name = p?.name || 'Unknown Product';
    }
  }

  const { error: itemsErr } = await supabaseAdmin
    .from('order_items')
    .insert(orderItems);

  if (itemsErr) {
    console.error('Order items error:', itemsErr);
    // Rollback — delete the order (items trigger may have partially run)
    await supabaseAdmin.from('orders').delete().eq('id', order.id);
    return R.error(res, 'Failed to save order items. Order has been rolled back.');
  }

  // Build WhatsApp notification link for customer
  const { data: settings } = await supabaseAdmin
    .from('settings')
    .select('whatsapp_number, wa_template_order_placed, meezan_account_no, easypaisa_number, jazzcash_number')
    .single();

  const methodAccountMap = {
    meezan_bank: settings?.meezan_account_no,
    easypaisa:   settings?.easypaisa_number,
    jazzcash:    settings?.jazzcash_number,
  };
  const methodLabelMap = {
    meezan_bank: 'Meezan Bank',
    easypaisa:   'EasyPaisa',
    jazzcash:    'JazzCash',
  };

  const waLink = buildWaLink(settings?.whatsapp_number, settings?.wa_template_order_placed, {
    Name:      customer_name,
    ORDER_NUM: order.order_number,
    Amount:    `PKR ${total_amount.toLocaleString()}`,
    Method:    methodLabelMap[payment_method],
    Bank:      methodLabelMap[payment_method],
    Account:   methodAccountMap[payment_method],
    LINK:      `${process.env.FRONTEND_URL || ''}/upload-payment?order=${order.order_number}`,
  });

  return R.created(res, {
    order_id:             order.id,
    order_number:         order.order_number,
    status:               order.status,
    total_amount:         order.total_amount,
    created_at:           order.created_at,
    whatsapp_message_link: waLink,
  });
});

// A8 — Public order tracking
router.get('/orders/track', validateQuery(trackOrderSchema), async (req, res) => {
  const { order_number } = req.query;

  const { data, error } = await supabaseAdmin
    .rpc('get_order_tracking', { p_order_number: order_number });

  if (error || !data || data.length === 0) {
    return R.notFound(res, 'Order not found. Please check the order number and try again.');
  }

  const row = data[0];
  return R.success(res, {
    order_number:         row.order_number,
    status:               row.status,
    tcs_tracking_number:  row.tcs_tracking_number,
    estimated_delivery:   row.estimated_delivery,
    steps: {
      order_placed:       row.step_order_placed,
      payment_submitted:  row.step_payment_submitted,
      payment_confirmed:  row.step_payment_confirmed,
      dispatched:         row.step_dispatched,
      delivered:          row.step_delivered,
    },
  });
});

module.exports = router;
